### ISSUE TITLE
Profile picture suggestions

### ISSUE THREAD

**Issue by abcdan** [sonofice/bashinfoscript#3]
I can't make issues on your profile because you don't have a repo named `sonofice` but I can make one here.

My issue is that you have no profile picture which makes it hard to distinguish you from the other people on this platform. Maybe @lukasvdberk can suggest a good profile picture for you to use.

**Comment by lukasvdberk** [comment]
I agree with @abcdan .  I have some suggestions for great profile pictures, these are the following:
![image](https://user-images.githubusercontent.com/38686669/118111738-68607780-b3e4-11eb-919b-24d70ebfc2ea.png)
![image](https://user-images.githubusercontent.com/38686669/118111747-6b5b6800-b3e4-11eb-83e8-dff03cf1be4a.png)
![image](https://user-images.githubusercontent.com/38686669/118111802-7b734780-b3e4-11eb-82c0-dee5eba8b9b4.png)

**Comment by abcdan** [comment]
I highly recommend the last one

**Comment by lukasvdberk** [comment]
I agree. The last one is a really sexy man!

**Comment by lukasvdberk** [comment]
Any updates on this?

**Comment by lukasvdberk** [comment]
**_My new suggestions please take these in considertation!_**

![afbeelding](https://user-images.githubusercontent.com/38686669/118380793-fefb8700-b5e4-11eb-8d7a-5c00c37c8d39.png)
![afbeelding](https://user-images.githubusercontent.com/38686669/118380798-0753c200-b5e5-11eb-9ca1-0348e5533f4e.png)
![afbeelding](https://user-images.githubusercontent.com/38686669/118380803-0cb10c80-b5e5-11eb-9916-847144bb75d1.png)
![afbeelding](https://user-images.githubusercontent.com/38686669/118380806-16d30b00-b5e5-11eb-8d0d-bdfe810f943f.png)
![afbeelding](https://user-images.githubusercontent.com/38686669/118380809-1c305580-b5e5-11eb-85a8-016225a898bc.png)

**Comment by lukasvdberk** [comment]
_**euma met reuma**_ themed profile pictures

![afbeelding](https://user-images.githubusercontent.com/38686669/118380829-4da92100-b5e5-11eb-8deb-099a96ac2336.png)
![afbeelding](https://user-images.githubusercontent.com/38686669/118380832-500b7b00-b5e5-11eb-9f87-0a49c4f91eab.png)
![afbeelding](https://user-images.githubusercontent.com/38686669/118380835-53066b80-b5e5-11eb-8b07-11d138964fc1.png)

**Comment by lukasvdberk** [comment]
Or take these beautiful man as your pf :)

![afbeelding](https://user-images.githubusercontent.com/38686669/118380847-69142c00-b5e5-11eb-92e0-6d7f9e7d77f3.png)
![afbeelding](https://user-images.githubusercontent.com/38686669/118380849-6ca7b300-b5e5-11eb-844c-19f195b802c6.png)
![afbeelding](https://user-images.githubusercontent.com/38686669/118380852-716c6700-b5e5-11eb-8ab9-c335027cc361.png)
![afbeelding](https://user-images.githubusercontent.com/38686669/118380853-73cec100-b5e5-11eb-939e-de78be7f26f3.png)

**Comment by lukasvdberk** [comment]
![random-jochie-vliegtuig](https://user-images.githubusercontent.com/38686669/118380941-3d457600-b5e6-11eb-839e-fbf2a0d8da7b.png)

**Comment by lukasvdberk** [comment]
![prachtige-creatie-kaas](https://user-images.githubusercontent.com/38686669/118381032-1a679180-b5e7-11eb-8704-da2c1b53048a.png)

**Comment by lukasvdberk** [comment]
100% recommend this one

![de beste creatie](https://user-images.githubusercontent.com/38686669/118381142-3455a400-b5e8-11eb-8a31-da2341d93d65.png)

**Comment by lukasvdberk** [comment]
My final offer!

![de echte beste creatie yes yes 2 uur snachts is me shit kaas op een broodje met een callipo](https://user-images.githubusercontent.com/38686669/118381179-944c4a80-b5e8-11eb-914c-fd6b7e8caf66.png)

**Comment by lukasvdberk** [comment]
mister patati head

![perfect man yes yes](https://user-images.githubusercontent.com/38686669/118381351-594b1680-b5ea-11eb-9be1-31158537e4ae.png)

**Comment by lukasvdberk** [comment]
That was really my final offering

**Comment by lukasvdberk** [comment]
![perfect man yes yes](https://media.tenor.com/images/2cb406e7619b591b7f7ca89b51989f57/tenor.gif)

**Comment by lukasvdberk** [comment]
So when is this issue gonna get closed and resolved?

**Comment by lukasvdberk** [comment]
![mega mindy TO THE MOON](https://user-images.githubusercontent.com/38686669/118381527-02ded780-b5ec-11eb-901d-ade2135d43b5.png)

**Comment by lukasvdberk** [comment]
![MINDY COIN TO THE MOON](https://user-images.githubusercontent.com/38686669/118381605-bb0c8000-b5ec-11eb-9b34-a1e20e1bf975.png)

**Comment by lukasvdberk** [comment]
Sorry for the random pictures my account got hacked by mega mindy!

**Comment by lukasvdberk** [comment]
![minecraft steve](https://user-images.githubusercontent.com/38686669/118381631-045ccf80-b5ed-11eb-960b-2c734e552621.png)

**Comment by abcdan** [comment]
Any update on this @sonofice

**Comment by abcdan** [comment]
@sonofice We are still waiting for a responz

**Comment by lukasvdberk** [comment]
@sonofice Any update on this?

**Comment by lukasvdberk** [comment]
Yehes we hebben hem!

**Comment by abcdan** [comment]
WE HEBBEN HEM

**Comment by lukasvdberk** [comment]
sheesh

**Comment by abcdan** [comment]
> sheesh

ongelofelijk lukas

**Comment by lukasvdberk** [comment]
![afbeelding](https://user-images.githubusercontent.com/38686669/159080811-1b57b3b1-693f-457a-bddd-2a09822901c8.png)

**Comment by sonofice** [comment]
> > sheesh
> 
> ongelofelijk lukas

sheeeeeeeesh

**Comment by lukasvdberk** [comment]
![](https://c.tenor.com/nYAbPZ6Im4YAAAAd/uwu-cute.gif)

**Comment by sonofice** [comment]
Outdated issue
